### ISSUE TITLE
Delete icon in admin configuration UI looks odd

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-custom-attributes#22]
When using the new admin configuration UI to manage custom attributes, the icon to delete a records looks strange. This makes the UI unclear. The icon should be replaced with one that is rotated clockwise 45 degrees. 

![Delete](https://user-images.githubusercontent.com/35588783/75375328-d54d2780-589b-11ea-9688-75eee89cc391.PNG)

**Comment by aaronrothschild** [comment]
@DHaussermann :+7:

**Comment by marianunez** [comment]
I'm surprised about that because it was showing like this for my PR https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/18 that introduced this feature: 

![](https://user-images.githubusercontent.com/936315/73415332-82ee0a80-42df-11ea-85dd-23cbbf6c61e4.png)

Will take a look again on latest master to see if there was anything that was changed there that could have affected that.

**Comment by marianunez** [comment]
@DHaussermann I'm still seeing the icon as expected with the latest of the plugin and WebApp: 

<img width="915" alt="Screen Shot 2020-02-28 at 12 25 43 PM" src="https://user-images.githubusercontent.com/936315/75570645-8c28df00-5a25-11ea-9b7c-7f4bcab162f3.png">

Any other specifics on how to reproduce this?

**Comment by DHaussermann** [comment]
@marianunez interesting.  Is it possible to DM me the server and credentials so I can try and isolate this?

**Comment by DHaussermann** [comment]
This issue repros on Windows but not Mac. 
Seems like we don't serve an image but rather rely on something provided by a font the OS has. 

![DeleteIcon](https://user-images.githubusercontent.com/35588783/75578902-bcc34580-5a32-11ea-82f6-5542f8174bae.PNG)

**Comment by aaronrothschild** [comment]
@asaadmahmood Do you have any idea what we should do here?  Should we use a trash can instead?  SVG needed if it's not a system graphic.

**Comment by asaadmahmood** [comment]
Yes, a trash can would be good.
We can use the trashcan like:
`<i class="fa fa-trash"></i>`

**Comment by marianunez** [comment]
Opened a PR for this: https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/23
