### ISSUE TITLE
What are considered as groups for this plugin?

### ISSUE THREAD

**Issue by theriverman** [mattermost/mattermost-plugin-custom-attributes#24]
The README states the following:
  > You can also add an array of Mattermost group ID's to the GroupIDs parameter. The Name will then be displayed for all memebers who are apart of that group.

I do not know about the existence of groups in Mattermost, the search in System Console does not bring up anything. All I can think of are `Teams` and `Channels`.
There are also `AD/LDAP Groups`, but such limitation (no teams edition support) is not stated in the README.

Thanks!

**Comment by hahmadia** [comment]
@theriverman 
Hello! Thanks for pointing out this issue. 
You are absolutely right and this was a missed when writing up the README regarding this. Yes, the Mattermost Groups are created from the AD/LDAP groups which is feature only available to our E20 customers. We should update the README to mention this and further hide the Groups field if the user doesn't have an E20 license. Great catch and thanks for that pointer.

**Comment by theriverman** [comment]
@hahmadia 
Thanks for picking up this case and coordinating its update!

**Comment by aaronrothschild** [comment]
Updated here: https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/38
