### ISSUE TITLE
Custom Profile Attributes are not showing up

### ISSUE THREAD

**Issue by songz** [mattermost/mattermost-plugin-custom-attributes#25]
Hi, I can't get the custom user attributes plugin to work. Here's what I did:

1. enabled the plugin in admin console.
2. I added the example [here](https://github.com/mattermost/mattermost-plugin-custom-attributes/#usage) (but I did not add groupId because I'm not sure what groupId is). 
3. Restarted the server with `sudo systemctl restart mattermost` and then  I click on a user, and my custom attribute did not show up.

Version 5.20.1
Schema Version: 5.20.0
Postgres

**Comment by aaronrothschild** [comment]
Hey @songz Can you send in the relevant part of your config.json or a screencap of the config screen?   Also check your log files for any errors.

**Comment by terafirmanz** [comment]
I also have this. install plugin add attribute and under username put in '@<myusername>' save
no luck
restart servers
no luck

Also there is no explanation on if group ID is the groups internal ID in the database (hope not as that is not easy to obtain) or the group name as it show sin the UI

**Comment by larkox** [comment]
@songz @terafirmanz 
With the latest version (v1.20) you should be able to add groups from the plugin settings site (check the README). Can you confirm this work for you?

**Comment by terafirmanz** [comment]
not sure why but mine started working after awhile. Took the group ID form the URL when editing properties of a group and that works.

**Comment by larkox** [comment]
@terafirmanz Do you think we can consider this issue closed?

**Comment by terafirmanz** [comment]
Form my perspective it is not sure if @songz still has issues but I would not consider there to be a bug.
