### ISSUE TITLE
Add confirmation dialogue when deleting groups from admin side UI

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-custom-attributes#26]
When an admin deletes a Custom Attributes group, there is no confirmation dialogue. Since this action cannot be undone, the user should be prompted to confirm the delete.

**Comment by hanzei** [comment]
@DHaussermann I've made this into a HW

**Comment by nathanaelhoun** [comment]
Hi! Is that a duplicate of #54?

**Comment by hanzei** [comment]
Indeed. Thanks for the hint @nathanaelhoun :+1:

**Comment by hanzei** [comment]
Duplicate of https://github.com/mattermost/mattermost-plugin-custom-attributes/issues/54
