### ISSUE TITLE
Custom attributes visible next to user's name

### ISSUE THREAD

**Issue by unode** [mattermost/mattermost-plugin-custom-attributes#31]
Hi everyone,

I'm looking for a mattermost plugin that allows decorating the user's name with arbitrary messages/symbols/emoji representing different status in the community.
If using emoji, these could be :star: (moderators), :+1: (supporters), and so on.

The current plugin already provides most of the customization capabilities I'm after but I do not see any mention of the ability to display the information next to the user's name.
Note that by this I mean, shown next to the name on every message written by the user, not in the floating pop-up with the profile information.

Is this something that can be achieved with the current plugin and/or mattermost's customization capabilities?

Thanks

**Comment by marquiswang** [comment]
In terms of spec, I propose the following change to the settings:

        "com.mattermost.custom-attributes": {
            "CustomAttributes": [
                {
                    "Name": ":mattermost: [Core Committer](https://developers.mattermost.com/contribute/getting-started/core-committers/)",
                    "UserIDs": ["someuserID1", "someuserID2"],
                    "GroupIDs":["somegroupID1","somegroupID2"],
                    "ShowBadge": true
                },
                {
                    "Name": ":mattermost: Staff",
                    "UserIDs": ["someuserID3", "someuserID4"],
                    "GroupIDs":["somegroupID3","somegroupID4"]
                }
            ]
        }

where an attribute with ShowBadge = true is visible in all channels.

**Comment by marquiswang** [comment]
I can help with a PR for this, but would need some pointers about the best way to implement this. I don't see an obvious option for setting post flair in the plugin registry (https://developers.mattermost.com/extend/plugins/webapp/reference/#registry)

Presumably it would make a lot of sense to hook into the code that generates the [BOT] badge for posts from the API.

**Comment by unode** [comment]
Instead of a boolean for `ShowBadge`, would it make more sense to have the variable hold the actual badge (e.g. `"ShowBadge": ":star:"`) ?
This would allow customizing the icon or text to be shown.

Perhaps unnecessary but I would also consider `"BadgeLocation" : "left|middle|right"`, to have the badge positioned in one of three locations: `(left) FirstName (middle) LastName (right)`.

**Comment by moschlar** [comment]
We're also interested in this!

**Comment by unode** [comment]
Since opening this issue mattermost implemented user roles. That covers most of our needs.

I would then close this. If anyone else is still waiting for this feature, feel free to reopen.
