### ISSUE TITLE
Add confirmation prompt when deleting a custom attributes record

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-custom-attributes#54]
When a custom attribute us deleted from the system console, no confirmation dialogue is shown to prevent user error. Since this action can't be undone (and the record could contain long cryptic lists of metadata), there should be a prompt top prevent deleting an attribute by mistake. 

Steps:
- Navigate to the admin side UI and select, Custom Attributes from the LHS
- Create a custom attribute
- Click the delete icon on the far right

**Observed**: Attribute is immediately deleted
**Expected**: delete confirmation dialogue

**Comment by DHaussermann** [comment]
@hanzei this may make a good help wanted issue. There may be other system console areas with a pattern for this that can be used here.

**Comment by icy-meteor** [comment]
Hey, 
I would like to pick this up :)

**Comment by larkox** [comment]
Great! :tada: All yours. If you need any help, do not hesitate to ask!

**Comment by icy-meteor** [comment]
Thank you @larkox! 
I have a created a PR for the same - https://github.com/mattermost/mattermost-plugin-custom-attributes/pull/55

P.S: This is my first PR to anything related to mattermost :) 
Let me know your feedback or if I have missed out on anything.

**Comment by icy-meteor** [comment]
Oops, I just noticed that there are some linting errors. Sorry about it, new to this :/ 
I will fix them and update the PR.
