### ISSUE TITLE
Custom Attribute section is not visible

### ISSUE THREAD

**Issue by sureshveernala** [mattermost/mattermost-plugin-custom-attributes#56]
After installing the custom attribute plugin, we enabling the plugin but can't see the custom attributes section.

**Comment by marianunez** [comment]
@sureshveernala the custom attribute section is not visible in the configuration screen in the System Console?
What Mattermost version are you seeing this issue in?

**Comment by sureshveernala** [comment]
> @sureshveernala the custom attribute section is not visible in the configuration screen in the System Console?
> What Mattermost version are you seeing this issue in?

**Comment by aaronrothschild** [comment]
@sureshveernala - Just curious, what solved this issue?

**Comment by sureshveernala** [comment]
> @sureshveernala the custom attribute section is not visible in the configuration screen in the System Console?
> What Mattermost version are you seeing this issue in?

version 5.23.1

**Comment by sureshveernala** [comment]
> @sureshveernala - Just curious, what solved this issue?

issue not resolved

**Comment by catalintomai** [comment]
> cc\ @catalintomai This seems to be the same as https://mattermost.atlassian.net/browse/MM-28871

@sureshveernala - could not repro the issue on 5.27/5.28, can you help confirm? Thanks.

**Comment by sureshveernala** [comment]
@catalintomai I can't understand what you are asking. Can you ask more clearly?

**Comment by nandeep12345** [comment]
@catalintomai @sureshveernala I am also facing the same issue.. 
I am getting the following error when installing the plugin

```
"msg":"Failed to notify cluster on plugin enable","error":"GetPluginStatus: Plugin is not installed., "
```
But when U checked config.json which Iam maintaining in database, it showing plugin as installed.

Can anyone help me. TIA

**Comment by catalintomai** [comment]
> @catalintomai I can't understand what you are asking. Can you ask more clearly?

@sureshveernala, you were mentioning above that you are using MM version version 5.23.1. I was asking you if you can try testing the same on MM versions 5.27/5.28 (since I cannot repro it on these later versions).

**Comment by catalintomai** [comment]
> @catalintomai @sureshveernala I am also facing the same issue..
> I am getting the following error after enabling the plugin and I could not see custom attributes settings section
> 
> ```
> "msg":"Failed to notify cluster on plugin enable","error":"GetPluginStatus: Plugin is not installed., "
> ```
> 
> But when I checked config.json which Iam maintaining in database, it showing plugin as installed.
> 
> Can anyone help me. TIA

@nandeep12345, we would need more info wrt to your setup: which MM+plugin version+edition, environment, the exact steps (install+activation), more detailed logs, what steps have you tried to fix the issue (e.g. did you try removing the local plugin manually and reinstall, etc.)

**Comment by devact** [comment]
@sureshveernala @marianunez 
Same issue here.

```
Mattermost Version: 5.29.0  
Database Schema Version: 5.29.0  
Database: mysql  
Free edition, installed on our server, CentOS7
Custom User Attributes (com.mattermost.custom-attributes - 1.3.0)
```

During the installation everything went fine in Systems Console. No errors.
When I try to add a new custom field - It's visible in the System Console and in config.json
↓
![553](https://user-images.githubusercontent.com/377895/102351145-a6c94600-3fae-11eb-9c3f-73999a3d3731.jpg)

But I receive this notice in the log when I click Save on the above screenshot:

```
{"level":"info","ts":1608122749.4361625,"caller":"go-plugin@v1.3.0/stream.go:15","msg":"2020/12/16 12:45:49 LoadPluginConfiguration API failed to unmarshal: json: cannot unmarshal string into Go struct field CustomAttribute.CustomAttributes.GroupIDs of type []string","plugin_id":"com.mattermost.custom-attributes","source":"plugin_stderr"}
```
And nothing is visible in users Account Settings:
↓
![554](https://user-images.githubusercontent.com/377895/102351708-906fba00-3faf-11eb-9d43-c92a3d7442c3.jpg)

**Comment by marianunez** [comment]
Hi @devact! Once you configure a custom field in the System Console, you should see it in the user popover as shown in the example [here](https://github.com/mattermost/mattermost-plugin-custom-attributes#mattermost-custom-attributes-plugin) 

Are you able to see your added attribute there?
